#ifndef MACROINSTANCER_H
#define MACROINSTANCER_H

#include "macromodules.h"

struct InstanceResult
{
    bool success;
};

/*
 * An assembly code line object must have a 1-1 mapping with a memory address.
 * In the (macro) code lines generated by previous compilation steps, a single macro
 * may be referenced by multiple lines of code, and therefore have multiple addresses.
 *
 * This class duplicates the passed in module assembly graph, and creates copies of code objects
 * so that the 1-1 mapping holds.
 */
class MacroInstancer
{
public:
    MacroInstancer();
    InstanceResult instance(ModuleAssemblyGraph& graph);
    InstanceResult instanceModule(ModuleAssemblyGraph graph, ModuleAssemblyGraph::InstanceMap& newMap,
                        ModuleInstance& instance);
};

#endif // MACROINSTANCER_H
